---
title: <center>About
output: html_document
---

<!--- please edit as needed!--->

----

## How healthy are our oceans?

Determining ocean health requires an approach that integrates social, economic, and environmental information. The Ocean Health Index (OHI) does this by measuring progress towards widely held goals that represent key benefits and services provided by marine ecosystems. By analyzing these goals together we obtain a comprehensive picture of the state of the ecosystem. 

<br>

## Assessing ocean health in Toolbox Demo
 
We are building a scientifically robust assessment of ocean health for Toolbox Demo. The OHI framework facilitates transparent and repeatable assessments of ocean health over time, and can be integrated into ongoing policy initiatives to support sustainable ocean management. We will build from previous OHI assessments and tailor the OHI framework to represent the cultural, social, and ecological characteristics and priorities of Toolbox Demo using the best available information and knowledge.

We will use this website to share our work in progress, as well as the final results. Our code is available [here](https://github.com/OHI-Science/toolbox-demo).

<br>

## The Ocean Health Index project

The Ocean Health Index is a way to combine social, economic, and environmental data to measure progress towards a suite of benefits people expect healthy oceans to provide – including seafood, protection from storms, and employment. Every year since 2012, the OHI team has tracked change in global ocean health for 220 coastal nations and territories. The team is also helping build a growing network of independent groups around the world to use the OHI to understand their own oceans. 

Learn more and explore ongoing assessments at [ohi-science.org](http://ohi-science.org). Additionally, read our publications about [best practices for assessing ocean health](https://peerj.com/articles/1503/) and [how OHI assessments are transparent and repeatable](https://www.nature.com/articles/s41559-017-0160). A full list of publications is available [here](http://ohi-science.org/publications).
